/**
 * ShowToday AI Analytics - Mock Scoring Data
 * Тестовые данные для системы скоринга
 */

import type {
  Manager,
  Targetologist,
  Placement,
  Creative,
  AIRecommendation,
  FunnelStageData,
  LeadSource,
  Lead,
  DashboardMetrics,
} from '../types/scoring';

// ===== МЕНЕДЖЕРЫ =====

export const MOCK_MANAGERS: Manager[] = [
  {
    id: 'mgr-1',
    name: 'Марат Ахметов',
    avatar: undefined,
    department: 'Продажи',
    metrics: {
      totalLeads: 45,
      totalDeals: 18,
      totalRevenue: 2890000,
      avgResponseTime: 6.2,
      totalMessages: 312,
      clientMessages: 156,
      aiQualityScore: 7.2,
    },
    scores: {
      conversion: 72,
      avgCheck: 68,
      responseSpeed: 78,
      engagement: 65,
      quality: 72,
    },
    totalScore: 71,
    rank: 'B',
    trend: 'up',
    trendValue: 3,
    aiInsight: 'Хорошие показатели, но есть куда расти. Время ответа чуть выше нормы в выходные дни.',
    recommendations: [
      'Настроить автоответ в нерабочее время',
      'Фокус на апсейл дополнительных услуг',
    ],
  },
  {
    id: 'mgr-2',
    name: 'Динара Касымова',
    avatar: undefined,
    department: 'Продажи',
    metrics: {
      totalLeads: 52,
      totalDeals: 14,
      totalRevenue: 1680000,
      avgResponseTime: 12.5,
      totalMessages: 328,
      clientMessages: 195,
      aiQualityScore: 5.8,
    },
    scores: {
      conversion: 48,
      avgCheck: 52,
      responseSpeed: 45,
      engagement: 62,
      quality: 58,
    },
    totalScore: 52,
    rank: 'C',
    trend: 'down',
    trendValue: -6,
    aiInsight: 'Проблема: время ответа выросло до 12+ минут. Клиенты уходят к конкурентам. Много незакрытых диалогов.',
    recommendations: [
      'Срочно улучшить скорость ответа',
      'Разобрать 8 "зависших" лидов',
      'Пройти курс по закрытию сделок',
    ],
  },
  {
    id: 'mgr-3',
    name: 'Бахытжан Серикулы',
    avatar: undefined,
    department: 'Продажи',
    metrics: {
      totalLeads: 38,
      totalDeals: 8,
      totalRevenue: 980000,
      avgResponseTime: 22.4,
      totalMessages: 145,
      clientMessages: 89,
      aiQualityScore: 4.2,
    },
    scores: {
      conversion: 32,
      avgCheck: 52,
      responseSpeed: 25,
      engagement: 38,
      quality: 42,
    },
    totalScore: 35,
    rank: 'D',
    trend: 'down',
    trendValue: -18,
    aiInsight: 'КРИТИЧНО: Конверсия упала с 45% до 21% за месяц. Не отвечает на лиды в течение 20+ мин. Теряем 65% входящих.',
    recommendations: [
      'Провести беседу о KPI',
      'Назначить наставника',
      'Рассмотреть перевод на другую позицию',
    ],
  },
  {
    id: 'mgr-4',
    name: 'Айжан Нурланова',
    avatar: undefined,
    department: 'Продажи',
    metrics: {
      totalLeads: 28,
      totalDeals: 11,
      totalRevenue: 1520000,
      avgResponseTime: 4.8,
      totalMessages: 218,
      clientMessages: 142,
      aiQualityScore: 6.8,
    },
    scores: {
      conversion: 62,
      avgCheck: 58,
      responseSpeed: 85,
      engagement: 68,
      quality: 68,
    },
    totalScore: 66,
    rank: 'B',
    trend: 'stable',
    trendValue: 1,
    aiInsight: 'Стабильная работа. Быстро отвечает, но средний чек ниже команды. Нужна работа над ценностью предложения.',
    recommendations: [
      'Изучить техники апсейла',
      'Больше фокуса на премиум-услуги',
    ],
  },
];

// ===== ТАРГЕТОЛОГИ =====

export const MOCK_TARGETOLOGISTS: Targetologist[] = [
  {
    id: 'tgt-1',
    name: 'Алия Сарсенова',
    avatar: undefined,
    campaigns: [
      { id: 'c1', name: 'Свадьбы 2026', spend: 285000, leads: 78, conversions: 24, revenue: 1850000 },
      { id: 'c2', name: 'Корпоративы', spend: 165000, leads: 45, conversions: 15, revenue: 980000 },
    ],
    metrics: {
      totalCampaigns: 5,
      totalSpend: 450000,
      totalRevenue: 2830000,
      totalLeads: 123,
      totalConversions: 39,
      avgCTR: 2.1,
      avgCPL: 3659,
    },
    scores: {
      trafficQuality: 82,
      roi: 88,
      cpl: 75,
      ctr: 70,
    },
    totalScore: 80,
    rank: 'A',
    trend: 'up',
    trendValue: 12,
    aiInsight: 'Отличный ROI на свадебной тематике. Рекомендуется масштабировать кампанию "Свадьбы 2026".',
    recommendations: [
      'Увеличить бюджет на Reels',
      'Создать Lookalike на конвертированных',
    ],
  },
  {
    id: 'tgt-2',
    name: 'Ернар Муратов',
    avatar: undefined,
    campaigns: [
      { id: 'c3', name: 'Детские праздники', spend: 180000, leads: 32, conversions: 5, revenue: 320000 },
      { id: 'c4', name: 'Дни рождения', spend: 95000, leads: 28, conversions: 8, revenue: 480000 },
    ],
    metrics: {
      totalCampaigns: 4,
      totalSpend: 275000,
      totalRevenue: 800000,
      totalLeads: 60,
      totalConversions: 13,
      avgCTR: 1.2,
      avgCPL: 4583,
    },
    scores: {
      trafficQuality: 52,
      roi: 45,
      cpl: 48,
      ctr: 40,
    },
    totalScore: 48,
    rank: 'C',
    trend: 'down',
    trendValue: -18,
    aiInsight: 'Кампания "Детские праздники" сливает бюджет — 180K потрачено, ROI отрицательный.',
    recommendations: [
      'Остановить "Детские праздники"',
      'Пересмотреть аудиторию',
      'Обновить креативы',
    ],
  },
];

// ===== ПЛЕЙСМЕНТЫ =====

export const MOCK_PLACEMENTS: Placement[] = [
  {
    id: 'pl-1',
    type: 'instagram_reels',
    name: 'Instagram Reels',
    icon: '🎬',
    metrics: {
      impressions: 245000,
      clicks: 7840,
      leads: 62,
      conversions: 28,
      spend: 185000,
      revenue: 1680000,
    },
    scores: {
      ctr: 92,
      conversionRate: 88,
      roi: 95,
      efficiency: 90,
    },
    totalScore: 92,
    recommendation: 'scale',
    trend: 'up',
    trendValue: 15,
    aiInsight: 'Лучший плейсмент по всем метрикам. Увеличивайте бюджет.',
  },
  {
    id: 'pl-2',
    type: 'instagram_stories',
    name: 'Instagram Stories',
    icon: '📱',
    metrics: {
      impressions: 189000,
      clicks: 3402,
      leads: 38,
      conversions: 15,
      spend: 120000,
      revenue: 890000,
    },
    scores: {
      ctr: 65,
      conversionRate: 72,
      roi: 78,
      efficiency: 70,
    },
    totalScore: 72,
    recommendation: 'maintain',
    trend: 'stable',
    trendValue: 2,
    aiInsight: 'Стабильные результаты. Поддерживайте текущий бюджет.',
  },
  {
    id: 'pl-3',
    type: 'instagram_feed',
    name: 'Instagram Feed',
    icon: '📸',
    metrics: {
      impressions: 156000,
      clicks: 3276,
      leads: 45,
      conversions: 18,
      spend: 145000,
      revenue: 1020000,
    },
    scores: {
      ctr: 68,
      conversionRate: 75,
      roi: 72,
      efficiency: 68,
    },
    totalScore: 70,
    recommendation: 'maintain',
    trend: 'down',
    trendValue: -5,
    aiInsight: 'Небольшое снижение CTR. Обновите креативы.',
  },
  {
    id: 'pl-4',
    type: 'facebook_feed',
    name: 'Facebook Feed',
    icon: '📘',
    metrics: {
      impressions: 98000,
      clicks: 1176,
      leads: 28,
      conversions: 8,
      spend: 95000,
      revenue: 480000,
    },
    scores: {
      ctr: 42,
      conversionRate: 55,
      roi: 58,
      efficiency: 50,
    },
    totalScore: 52,
    recommendation: 'optimize',
    trend: 'down',
    trendValue: -12,
    aiInsight: 'Низкий CTR и ROI. Требуется оптимизация таргетинга.',
  },
  {
    id: 'pl-5',
    type: 'facebook_marketplace',
    name: 'FB Marketplace',
    icon: '🛒',
    metrics: {
      impressions: 45000,
      clicks: 360,
      leads: 12,
      conversions: 2,
      spend: 65000,
      revenue: 120000,
    },
    scores: {
      ctr: 25,
      conversionRate: 32,
      roi: 28,
      efficiency: 25,
    },
    totalScore: 28,
    recommendation: 'pause',
    trend: 'down',
    trendValue: -25,
    aiInsight: 'Неэффективен для вашей аудитории. Рекомендуется отключить.',
  },
];

// ===== КРЕАТИВЫ =====

export const MOCK_CREATIVES: Creative[] = [
  {
    id: 'cr-1',
    name: 'Свадьба мечты — скидка 20%',
    type: 'video',
    thumbnail: 'https://images.unsplash.com/photo-1519741497674-611481863552?w=400&h=400&fit=crop',
    placementTypes: ['instagram_reels', 'instagram_stories'],
    metrics: {
      impressions: 156000,
      reach: 98000,
      clicks: 5928,
      leads: 48,
      conversions: 22,
      spend: 45000,
      revenue: 216000,
      likes: 2840,
      comments: 186,
      shares: 342,
      saves: 520,
      videoViews: 124000,
      avgWatchTime: 12.5,
      videoLength: 15,
    },
    scores: {
      roi: 95,
      engagementRate: 88,
      clickToLead: 82,
      thumbStopRate: 85,
      holdRate: 83,
    },
    totalScore: 92,
    status: 'top',
    frequency: 1.8,
    trend: 'up',
    trendValue: 18,
    aiInsight: 'Лучший креатив по ROI. Масштабируйте на Lookalike аудиторию.',
    recommendations: [
      'Создать похожий креатив для корпоративов',
      'Тестировать на Facebook',
    ],
  },
  {
    id: 'cr-2',
    name: 'Корпоратив под ключ',
    type: 'carousel',
    thumbnail: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=400&h=400&fit=crop',
    placementTypes: ['instagram_feed', 'facebook_feed'],
    metrics: {
      impressions: 98000,
      reach: 72000,
      clicks: 2058,
      leads: 35,
      conversions: 14,
      spend: 62000,
      revenue: 214000,
      likes: 1250,
      comments: 89,
      shares: 156,
      saves: 280,
    },
    scores: {
      roi: 78,
      engagementRate: 72,
      clickToLead: 75,
    },
    totalScore: 75,
    status: 'performing',
    frequency: 2.4,
    trend: 'stable',
    trendValue: 3,
    aiInsight: 'Стабильные показатели. Попробуйте видео-версию для Reels.',
    recommendations: [
      'Создать видео версию',
      'Добавить отзывы клиентов',
    ],
  },
  {
    id: 'cr-3',
    name: 'День рождения ребёнка',
    type: 'image',
    thumbnail: 'https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=400&h=400&fit=crop',
    placementTypes: ['instagram_feed', 'instagram_stories'],
    metrics: {
      impressions: 67000,
      reach: 45000,
      clicks: 938,
      leads: 18,
      conversions: 6,
      spend: 38000,
      revenue: 72000,
      likes: 580,
      comments: 42,
      shares: 68,
      saves: 95,
    },
    scores: {
      roi: 45,
      engagementRate: 48,
      clickToLead: 52,
    },
    totalScore: 48,
    status: 'declining',
    frequency: 4.2,
    trend: 'down',
    trendValue: -22,
    aiInsight: 'Креатив устал — частота 4.2. Обновите визуал или поставьте на паузу.',
    recommendations: [
      'Обновить изображение',
      'Сменить оффер',
      'Или поставить на паузу',
    ],
  },
  {
    id: 'cr-4',
    name: 'Летние вечеринки 2026',
    type: 'video',
    thumbnail: 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=400&h=400&fit=crop',
    placementTypes: ['instagram_reels'],
    metrics: {
      impressions: 42000,
      reach: 28000,
      clicks: 420,
      leads: 8,
      conversions: 1,
      spend: 28000,
      revenue: 15000,
      likes: 320,
      comments: 18,
      shares: 25,
      saves: 40,
      videoViews: 35000,
      avgWatchTime: 4.2,
      videoLength: 12,
    },
    scores: {
      roi: 18,
      engagementRate: 32,
      clickToLead: 28,
      thumbStopRate: 45,
      holdRate: 35,
    },
    totalScore: 28,
    status: 'fatigue',
    frequency: 5.8,
    trend: 'down',
    trendValue: -35,
    aiInsight: 'Критически низкие показатели. Частота 5.8 — аудитория устала. Остановите креатив.',
    recommendations: [
      'Остановить немедленно',
      'Создать новый креатив с другим подходом',
    ],
  },
];

// ===== AI РЕКОМЕНДАЦИИ =====

export const MOCK_RECOMMENDATIONS: AIRecommendation[] = [
  {
    id: 'rec-1',
    type: 'BUDGET_DRAIN',
    priority: 'critical',
    target: {
      type: 'campaign',
      id: 'c3',
      name: 'Детские праздники',
    },
    title: 'Слив бюджета — кампания убыточна',
    insight: 'Потрачено 180,000 ₸ за 5 дней — ROI отрицательный (-46%). Таргетинг настроен на мужчин 35-55, хотя ЦА — мамы 25-40.',
    recommendation: 'Остановить кампанию, пересмотреть аудиторию. После корректировки запустить с минимальным бюджетом для теста.',
    expectedImpact: 'Экономия 36,000 ₸/день',
    metrics: {
      current: -46,
      benchmark: 150,
      unit: '% ROI',
    },
    actions: [],
    confidence: 95,
    createdAt: new Date(),
  },
  {
    id: 'rec-2',
    type: 'MANAGER_UNDERPERFORM',
    priority: 'critical',
    target: {
      type: 'manager',
      id: 'mgr-3',
      name: 'Бахытжан Серикулы',
    },
    title: 'Критическое падение конверсии менеджера',
    insight: 'Конверсия упала с 45% до 21% за месяц. Время ответа 22+ минуты. Потеряно 24 лида за последние 2 недели.',
    recommendation: 'Провести личную беседу. Выяснить причины (выгорание, личные проблемы). Назначить наставника или рассмотреть перевод.',
    expectedImpact: 'Потенциально +12 сделок/месяц при восстановлении показателей',
    metrics: {
      current: 21,
      benchmark: 45,
      unit: '% конверсия',
    },
    actions: [],
    confidence: 92,
    createdAt: new Date(),
  },
  {
    id: 'rec-3',
    type: 'SCALE_OPPORTUNITY',
    priority: 'high',
    target: {
      type: 'campaign',
      id: 'c1',
      name: 'Свадьбы 2026',
    },
    title: 'Возможность масштабирования',
    insight: 'ROI 185%, частота показа 1.8 — есть запас. Конверсия стабильная последние 3 недели.',
    recommendation: 'Увеличить дневной бюджет на 20-25%. Создать Lookalike аудиторию на базе покупателей.',
    expectedImpact: '+5-7 сделок/неделю при текущей конверсии',
    metrics: {
      current: 185,
      benchmark: 150,
      unit: '% ROI',
    },
    actions: [],
    confidence: 78,
    createdAt: new Date(),
  },
  {
    id: 'rec-4',
    type: 'CREATIVE_FATIGUE',
    priority: 'medium',
    target: {
      type: 'creative',
      id: 'cr-3',
      name: 'День рождения ребёнка',
    },
    title: 'Креатив устал — нужно обновление',
    insight: 'Частота показа 4.2, CTR упал на 22% за неделю. Аудитория видела рекламу слишком много раз.',
    recommendation: 'Обновить визуал с новыми фото/видео. Или сменить оффер на сезонный.',
    expectedImpact: 'Восстановление CTR на 15-20%',
    metrics: {
      current: 4.2,
      benchmark: 2.5,
      unit: 'частота',
    },
    actions: [],
    confidence: 75,
    createdAt: new Date(),
  },
  {
    id: 'rec-5',
    type: 'MANAGER_UNDERPERFORM',
    priority: 'medium',
    target: {
      type: 'manager',
      id: 'mgr-2',
      name: 'Динара Касымова',
    },
    title: 'Снижение скорости ответа',
    insight: 'Время ответа выросло с 5 до 12 минут за 2 недели. 8 "зависших" диалогов без ответа более 24 часов.',
    recommendation: 'Разобрать накопившиеся лиды. Настроить напоминания в CRM. Возможно, перегрузка — перераспределить лиды.',
    expectedImpact: 'Потенциально +3-4 сделки при улучшении',
    metrics: {
      current: 12,
      benchmark: 5,
      unit: 'мин ответа',
    },
    actions: [],
    confidence: 82,
    createdAt: new Date(),
  },
  {
    id: 'rec-6',
    type: 'PLACEMENT_SHIFT',
    priority: 'low',
    target: {
      type: 'placement',
      id: 'pl-5',
      name: 'FB Marketplace',
    },
    title: 'Низкая эффективность плейсмента',
    insight: 'CTR 0.8%, ROI ниже других плейсментов. Не приоритетный канал для event-услуг.',
    recommendation: 'При оптимизации бюджета — первый кандидат на отключение.',
    expectedImpact: 'Перераспределение 65K ₸ на более эффективные каналы',
    metrics: {
      current: 85,
      benchmark: 200,
      unit: '% ROI',
    },
    actions: [],
    confidence: 70,
    createdAt: new Date(),
  },
];

// ===== ВОРОНКА ПРОДАЖ =====

export const MOCK_FUNNEL: FunnelStageData[] = [
  { stage: 'traffic', name: 'Трафик', count: 2450, value: 0, spend: 485000, conversionRate: 100, avgTimeInStage: 0, color: '#6366F1' },
  { stage: 'leads', name: 'Лиды', count: 156, value: 0, spend: 0, conversionRate: 6.4, avgTimeInStage: 0.5, color: '#8B5CF6' },
  { stage: 'contacted', name: 'Первичное касание', count: 142, value: 0, spend: 12000, conversionRate: 91, avgTimeInStage: 2, color: '#A855F7' },
  { stage: 'qualified', name: 'Квалификация', count: 98, value: 0, spend: 0, conversionRate: 69, avgTimeInStage: 12, color: '#D946EF' },
  { stage: 'warm', name: 'Тёплые', count: 62, value: 0, spend: 25000, conversionRate: 63, avgTimeInStage: 24, color: '#EC4899' },
  { stage: 'deal', name: 'Сделки', count: 48, value: 7240000, spend: 0, conversionRate: 77, avgTimeInStage: 48, color: '#10B981' },
  { stage: 'lost', name: 'Потеряно', count: 14, value: 0, spend: 0, conversionRate: 23, avgTimeInStage: 0, color: '#EF4444' },
];

// ===== ДАННЫЕ ПО КАНАЛАМ ДЛЯ ВОРОНКИ =====
export type FunnelChannel = 'all' | 'instagram' | 'facebook' | 'google' | 'organic' | 'promo';

export interface ChannelFunnelData {
  channel: FunnelChannel;
  name: string;
  icon: string;
  color: string;
  funnel: FunnelStageData[];
  totalSpend: number;
  totalRevenue: number;
}

export const FUNNEL_BY_CHANNEL: ChannelFunnelData[] = [
  {
    channel: 'instagram',
    name: 'Instagram Ads',
    icon: '📸',
    color: '#E1306C',
    totalSpend: 285000,
    totalRevenue: 3650000,
    funnel: [
      { stage: 'traffic', name: 'Трафик', count: 1250, value: 0, spend: 285000, conversionRate: 100, avgTimeInStage: 0, color: '#6366F1' },
      { stage: 'leads', name: 'Лиды', count: 68, value: 0, spend: 0, conversionRate: 5.4, avgTimeInStage: 0.5, color: '#8B5CF6' },
      { stage: 'contacted', name: 'Первичное касание', count: 62, value: 0, spend: 5000, conversionRate: 91, avgTimeInStage: 2, color: '#A855F7' },
      { stage: 'qualified', name: 'Квалификация', count: 45, value: 0, spend: 0, conversionRate: 73, avgTimeInStage: 10, color: '#D946EF' },
      { stage: 'warm', name: 'Тёплые', count: 32, value: 0, spend: 12000, conversionRate: 71, avgTimeInStage: 20, color: '#EC4899' },
      { stage: 'deal', name: 'Сделки', count: 24, value: 3650000, spend: 0, conversionRate: 75, avgTimeInStage: 36, color: '#10B981' },
      { stage: 'lost', name: 'Потеряно', count: 8, value: 0, spend: 0, conversionRate: 25, avgTimeInStage: 0, color: '#EF4444' },
    ]
  },
  {
    channel: 'facebook',
    name: 'Facebook Ads',
    icon: '👤',
    color: '#1877F2',
    totalSpend: 95000,
    totalRevenue: 1240000,
    funnel: [
      { stage: 'traffic', name: 'Трафик', count: 580, value: 0, spend: 95000, conversionRate: 100, avgTimeInStage: 0, color: '#6366F1' },
      { stage: 'leads', name: 'Лиды', count: 32, value: 0, spend: 0, conversionRate: 5.5, avgTimeInStage: 0.5, color: '#8B5CF6' },
      { stage: 'contacted', name: 'Первичное касание', count: 28, value: 0, spend: 3000, conversionRate: 88, avgTimeInStage: 2, color: '#A855F7' },
      { stage: 'qualified', name: 'Квалификация', count: 18, value: 0, spend: 0, conversionRate: 64, avgTimeInStage: 14, color: '#D946EF' },
      { stage: 'warm', name: 'Тёплые', count: 12, value: 0, spend: 5000, conversionRate: 67, avgTimeInStage: 28, color: '#EC4899' },
      { stage: 'deal', name: 'Сделки', count: 9, value: 1240000, spend: 0, conversionRate: 75, avgTimeInStage: 48, color: '#10B981' },
      { stage: 'lost', name: 'Потеряно', count: 3, value: 0, spend: 0, conversionRate: 25, avgTimeInStage: 0, color: '#EF4444' },
    ]
  },
  {
    channel: 'google',
    name: 'Google Ads',
    icon: '🔍',
    color: '#4285F4',
    totalSpend: 65000,
    totalRevenue: 980000,
    funnel: [
      { stage: 'traffic', name: 'Трафик', count: 320, value: 0, spend: 65000, conversionRate: 100, avgTimeInStage: 0, color: '#6366F1' },
      { stage: 'leads', name: 'Лиды', count: 28, value: 0, spend: 0, conversionRate: 8.8, avgTimeInStage: 0.3, color: '#8B5CF6' },
      { stage: 'contacted', name: 'Первичное касание', count: 26, value: 0, spend: 2000, conversionRate: 93, avgTimeInStage: 1.5, color: '#A855F7' },
      { stage: 'qualified', name: 'Квалификация', count: 19, value: 0, spend: 0, conversionRate: 73, avgTimeInStage: 8, color: '#D946EF' },
      { stage: 'warm', name: 'Тёплые', count: 10, value: 0, spend: 4000, conversionRate: 53, avgTimeInStage: 18, color: '#EC4899' },
      { stage: 'deal', name: 'Сделки', count: 8, value: 980000, spend: 0, conversionRate: 80, avgTimeInStage: 40, color: '#10B981' },
      { stage: 'lost', name: 'Потеряно', count: 2, value: 0, spend: 0, conversionRate: 20, avgTimeInStage: 0, color: '#EF4444' },
    ]
  },
  {
    channel: 'organic',
    name: 'Органика',
    icon: '🌱',
    color: '#22C55E',
    totalSpend: 0,
    totalRevenue: 850000,
    funnel: [
      { stage: 'traffic', name: 'Трафик', count: 200, value: 0, spend: 0, conversionRate: 100, avgTimeInStage: 0, color: '#6366F1' },
      { stage: 'leads', name: 'Лиды', count: 18, value: 0, spend: 0, conversionRate: 9.0, avgTimeInStage: 0.5, color: '#8B5CF6' },
      { stage: 'contacted', name: 'Первичное касание', count: 17, value: 0, spend: 1000, conversionRate: 94, avgTimeInStage: 2, color: '#A855F7' },
      { stage: 'qualified', name: 'Квалификация', count: 11, value: 0, spend: 0, conversionRate: 65, avgTimeInStage: 12, color: '#D946EF' },
      { stage: 'warm', name: 'Тёплые', count: 6, value: 0, spend: 2000, conversionRate: 55, avgTimeInStage: 24, color: '#EC4899' },
      { stage: 'deal', name: 'Сделки', count: 5, value: 850000, spend: 0, conversionRate: 83, avgTimeInStage: 36, color: '#10B981' },
      { stage: 'lost', name: 'Потеряно', count: 1, value: 0, spend: 0, conversionRate: 17, avgTimeInStage: 0, color: '#EF4444' },
    ]
  },
  {
    channel: 'promo',
    name: 'Промо-акции',
    icon: '🎉',
    color: '#F59E0B',
    totalSpend: 40000,
    totalRevenue: 520000,
    funnel: [
      { stage: 'traffic', name: 'Трафик', count: 100, value: 0, spend: 40000, conversionRate: 100, avgTimeInStage: 0, color: '#6366F1' },
      { stage: 'leads', name: 'Лиды', count: 10, value: 0, spend: 0, conversionRate: 10.0, avgTimeInStage: 0.5, color: '#8B5CF6' },
      { stage: 'contacted', name: 'Первичное касание', count: 9, value: 0, spend: 1000, conversionRate: 90, avgTimeInStage: 1.5, color: '#A855F7' },
      { stage: 'qualified', name: 'Квалификация', count: 5, value: 0, spend: 0, conversionRate: 56, avgTimeInStage: 10, color: '#D946EF' },
      { stage: 'warm', name: 'Тёплые', count: 2, value: 0, spend: 2000, conversionRate: 40, avgTimeInStage: 20, color: '#EC4899' },
      { stage: 'deal', name: 'Сделки', count: 2, value: 520000, spend: 0, conversionRate: 100, avgTimeInStage: 24, color: '#10B981' },
      { stage: 'lost', name: 'Потеряно', count: 0, value: 0, spend: 0, conversionRate: 0, avgTimeInStage: 0, color: '#EF4444' },
    ]
  },
];

// ===== ИСТОЧНИКИ ЛИДОВ =====

export const MOCK_LEAD_SOURCES: LeadSource[] = [
  {
    id: 'src-1',
    name: 'Instagram Ads',
    icon: '📸',
    color: '#E1306C',
    leads: 68,
    conversions: 24,
    revenue: 3650000,
    spend: 285000,
    conversionRate: 35.3,
    roi: 1181,
    cpl: 4191,
  },
  {
    id: 'src-2',
    name: 'Google Ads',
    icon: '🔍',
    color: '#4285F4',
    leads: 42,
    conversions: 12,
    revenue: 1820000,
    spend: 165000,
    conversionRate: 28.6,
    roi: 1003,
    cpl: 3929,
  },
  {
    id: 'src-3',
    name: 'WhatsApp (органика)',
    icon: '💬',
    color: '#25D366',
    leads: 28,
    conversions: 8,
    revenue: 980000,
    spend: 0,
    conversionRate: 28.6,
    roi: Infinity,
    cpl: 0,
  },
  {
    id: 'src-4',
    name: 'Рекомендации',
    icon: '👥',
    color: '#FFD700',
    leads: 12,
    conversions: 4,
    revenue: 640000,
    spend: 0,
    conversionRate: 33.3,
    roi: Infinity,
    cpl: 0,
  },
  {
    id: 'src-5',
    name: 'Facebook Ads',
    icon: '📘',
    color: '#1877F2',
    leads: 6,
    conversions: 0,
    revenue: 150000,
    spend: 75000,
    conversionRate: 0,
    roi: 100,
    cpl: 12500,
  },
];

// ===== ЛИДЫ =====

export const MOCK_LEADS: Lead[] = [
  {
    id: 'lead-1',
    name: 'Асель Муратова',
    phone: '+7 705 123 4567',
    email: 'asel@mail.kz',
    source: 'Instagram Ads',
    sourceIcon: '📸',
    status: 'WARM',
    temperature: 'HOT',
    score: 85,
    assignedTo: 'Марат Ахметов',
    managerId: 'mgr-1',
    amount: 280000,
    createdAt: new Date('2026-01-28T14:30:00'),
    lastActivity: new Date('2026-01-29T09:15:00'),
    tags: ['свадьба', 'премиум'],
    notes: 'Интересуется пакетом "Всё включено"',
  },
  {
    id: 'lead-2',
    name: 'Тимур Касымов',
    phone: '+7 707 234 5678',
    source: 'Google Ads',
    sourceIcon: '🔍',
    status: 'QUALIFIED',
    temperature: 'WARM',
    score: 62,
    assignedTo: 'Динара Касымова',
    managerId: 'mgr-2',
    amount: 150000,
    createdAt: new Date('2026-01-28T11:00:00'),
    lastActivity: new Date('2026-01-28T16:45:00'),
    tags: ['корпоратив'],
  },
  {
    id: 'lead-3',
    name: 'Алия Сериккызы',
    phone: '+7 701 345 6789',
    source: 'WhatsApp',
    sourceIcon: '💬',
    status: 'NEW',
    temperature: 'COLD',
    score: 35,
    assignedTo: 'Айжан Нурланова',
    managerId: 'mgr-4',
    createdAt: new Date('2026-01-29T08:00:00'),
    lastActivity: new Date('2026-01-29T08:00:00'),
    tags: ['день рождения'],
  },
  {
    id: 'lead-4',
    name: 'ТОО "Астана Групп"',
    phone: '+7 717 456 7890',
    email: 'info@astanagroup.kz',
    source: 'Рекомендации',
    sourceIcon: '👥',
    status: 'WARM',
    temperature: 'HOT',
    score: 92,
    assignedTo: 'Марат Ахметов',
    managerId: 'mgr-1',
    amount: 850000,
    createdAt: new Date('2026-01-27T10:00:00'),
    lastActivity: new Date('2026-01-29T11:30:00'),
    tags: ['корпоратив', 'крупный клиент', 'B2B'],
    notes: 'Новогодний корпоратив на 200 человек',
  },
];

// ===== МЕТРИКИ ДАШБОРДА =====

export const MOCK_DASHBOARD_METRICS: DashboardMetrics = {
  totalLeads: 163,
  totalDeals: 51,
  totalRevenue: 7070000,
  conversionRate: 31.3,
  avgCheck: 138627,
  roi: 142,

  leadsChange: -5,
  dealsChange: 2,
  revenueChange: -8,
  conversionChange: -2,
};
